spring.application.name=ex-ch03

# ======================================
# Server
# ======================================
server.port=8090

# ======================================
# Encoding
# ======================================
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
server.servlet.encoding.force-request=true
server.servlet.encoding.force-response=true

# ======================================
# Logging
# ======================================
logging.level.root=info
logging.level.com.example.demo.service=debug

# Thymeleaf 비활성화, Mustache 활성화
spring.thymeleaf.cache=false
spring.mustache.enabled=true
spring.thymeleaf.enabled=false

spring.mustache.suffix=.mustache
spring.mustache.check-template-location=true

spring.mustache.prefix=classpath:/mustache-templates/
logging.level.org.springframework.web.servlet.view=DEBUG
logging.level.org.springframework.boot.autoconfigure.mustache=DEBUG



